/// English localization strings for Bagdja Wallet
library;

const Map<String, Map<String, String>> enStrings = {
  "lang": {"key": "en_US"},
  'login': {
    'title': 'Login',
    'loginWithSSO': 'Login with SSO',
  },
  'home': {
    'title': 'Wallet',
    'totalBalance': 'Total Balance',
    'myWallets': 'My Wallets',
    'recentMutation': 'Recent Mutation',
    'wallet': 'Wallet',
    'provider': 'Provider',
    'active': 'Active',
    'held': 'Held',
    'topUp': 'Top Up',
    'payment': 'Payment',
    'chooseAction': 'Choose Action',
    'topUpDescription': 'Top up your wallet balance',
    'refresh': 'Refresh',
    'createInvoice': 'Create Invoice',
    'createInvoiceDescription': 'Create invoice for customers',
    'createEscrow': 'Create Escrow',
    'createEscrowDescription': 'Create a secure escrow transaction',
    'invoiceHistory': 'Invoice History',
    'escrowHistory': 'Escrow History',
    'comingSoon': 'Coming Soon',
  },
  'wallet': {
    'balance': 'Balance',
    'currency': 'Currency',
  },
  'escrow': {
    'buyer': 'Buyer',
    'buyerIdentifier': 'Buyer Identifier',
    'seller': 'Seller',
    'sellerIdentifier': 'Seller Identifier',
    'amount': 'Amount',
    'notes': 'Notes',
    'create': 'Create Escrow',
    'created': 'Escrow created successfully!',
    'selectYourPosition': 'Select Your Position',
    'releaseConfirmMessage': 'Are you sure you want to release escrow funds to the seller?',
    'selectYourWallet': 'Select Your Wallet',
    'partnerPosition': 'Partner Position',
    'personal': 'Personal',
    'organization': 'Organization',
    'findUserOrOrgId': 'Find User / Org Id',
    'usernameValid': 'Username valid',
    'orgIdValid': 'Org ID valid',
    'usernameNotFound': 'Username not found',
    'orgIdNotFound': 'Org ID not found',
    'error': 'Error',
    'mine': 'Mine',
    'invited': 'Invited',
    'detailTitle': 'Escrow Detail',
    'status': 'Status',
    'escrowId': 'Escrow ID',
    'createdAt': 'Created at',
    'you': 'You',
    'payNow': 'Pay Now',
    'releaseFunds': 'Release Funds',
    'releaseSuccess': 'Escrow released successfully!',
  },
  'common': {
    'tryAgain': 'Try Again',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'noData': 'No Data',
  },
  'profile': {
    'title': 'Profile',
    'logout': 'Logout',
    'logoutConfirmDescription': 'Are you sure you want to logout?',
    'logoutConfirm': 'Logout Confirmation',
    'logoutConfirmConfirm': 'Logout',
    'logoutConfirmCancel': 'Cancel',
  },
};
