/// Indonesian localization strings for Bagdja Wallet
library;

const Map<String, Map<String, String>> idStrings = {
  "lang": {"key": "id_ID"},
  'login': {
    'title': 'Masuk',
    'loginWithSSO': 'Masuk dengan SSO',
  },
  'home': {
    'title': 'Dompet',
    'totalBalance': 'Total Saldo',
    'myWallets': 'Dompet Saya',
    'recentMutation': 'Mutasi Terbaru',
    'wallet': 'Dompet',
    'provider': 'Provider',
    'active': 'Aktif',
    'held': 'Ditahan',
    'topUp': 'Top Up',
    'payment': 'Pembayaran',
    'chooseAction': 'Pilih Aksi',
    'topUpDescription': 'Isi saldo wallet kamu',
    'createInvoice': 'Buat Invoice',
    'createInvoiceDescription': 'Buat invoice untuk pelanggan',
    'createEscrow': 'Buat Escrow',
    'createEscrowDescription': 'Buat transaksi escrow yang aman',
    'invoiceHistory': 'History Invoice',
    'escrowHistory': 'History Escrow',
    'comingSoon': 'Segera Hadir',
  },
  'wallet': {
    'balance': 'Saldo',
    'currency': 'Mata Uang',
  },
  'escrow': {
    'buyer': 'Pembeli',
    'buyerIdentifier': 'Identitas Pembeli',
    'seller': 'Penjual',
    'sellerIdentifier': 'Identitas Penjual',
    'amount': 'Jumlah',
    'notes': 'Catatan',
    'create': 'Buat Escrow',
    'created': 'Escrow berhasil dibuat!',
    'selectYourPosition': 'Pilih Posisi Anda',
    'selectYourWallet': 'Pilih Wallet Anda',
    'partnerPosition': 'Posisi Partner',
    'personal': 'Personal',
    'organization': 'Organisasi',
    'findUserOrOrgId': 'Cari Pengguna / Id Org',
    'usernameValid': 'engguna valid valid',
    'orgIdValid': 'Id Org valid',
    'usernameNotFound': 'Pengguna tidak ditemukan',
    'orgIdNotFound': 'Id Org tidak ditemukan',
    'error': 'Gagal',
    'mine': 'Saya',
    'invited': 'Diundang',
  },
  'common': {
    'tryAgain': 'Coba Lagi',
    'loading': 'Memuat...',
    'error': 'Gagal',
    'success': 'Berhasil',
    'noData': 'Tidak Ada Data',
  },
  'profile': {
    'title': 'Profil',
    'logout': 'Keluar',
    'logoutConfirmDescription': 'Apa anda yakin ingin keluar?',
    'logoutConfirm': 'Konfirmasi Keluar',
    'logoutConfirmConfirm': 'Keluar',
    'logoutConfirmCancel': 'Batal',
   },
};
